# Generated by Django 4.2.2 on 2024-09-17 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Контактный email"
                    ),
                ),
                ("last_name", models.CharField(max_length=20, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=20, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(max_length=20, verbose_name="Отчество"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_of_the_letter",
                    models.CharField(max_length=255, verbose_name="Тема письма"),
                ),
                ("body_of_the_letter", models.TextField(verbose_name="Тело письма")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(verbose_name="Дата и время начала рассылки"),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        verbose_name="Дата и время окончания рассылки"
                    ),
                ),
                (
                    "next_send_time",
                    models.DateTimeField(
                        verbose_name="Дата и время следующей отправки рассылки"
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("daily", "Ежедневно"),
                            ("weekly", "Еженедельно"),
                            ("monthly", "Ежемесячно"),
                        ],
                        max_length=10,
                        verbose_name="Периодичность рассылки письма",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("create", "Создана"),
                            ("launched", "Запущена"),
                            ("completed", "Завершена"),
                        ],
                        default="create",
                        max_length=10,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "client",
                    models.ManyToManyField(
                        to="mailing.client", verbose_name="Клиенты рассылки"
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_last_attempt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата последней попытки"
                    ),
                ),
                (
                    "last_attempt_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время последней попытки"
                    ),
                ),
                (
                    "attempt_status",
                    models.TextField(
                        choices=[("success", "Успешно"), ("failure", "Не успешно")],
                        max_length=10,
                        verbose_name="Статус попытки",
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="mailing.mailing",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="mailing.mailing",
                        verbose_name="Ответ почтового сервера, если он был",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка",
                "verbose_name_plural": "Попытки",
            },
        ),
    ]
