# Generated by Django 4.2.2 on 2024-09-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "permissions": [
                    (
                        "Can_view_the_list_of_service_users",
                        "Can view the list of service users",
                    ),
                    (
                        "May_block_users_of_the_service",
                        "May block users of the service",
                    ),
                ],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("Can_view_any_mailings", "Can view any mailings"),
                    ("Can_disable_mailings", "Can disable mailings"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [
                    ("Can_view_messages", "Can view messages"),
                    ("Can_edit_messages", "Can edit messages"),
                ],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
