# Generated by Django 4.2.2 on 2024-09-28 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_client_owner_mailing_owner_message_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "permissions": [
                    (
                        "man_view_the_list_of_service_users",
                        "can view the list of service users",
                    ),
                    (
                        "may_block_users_of_the_service",
                        "may block users of the service",
                    ),
                ],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_any_mailings", "Can view any mailings"),
                    ("can_disable_mailings", "Can disable mailings"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [
                    ("can_view_messages", "Can view messages"),
                    ("can_edit_messages", "Can edit messages"),
                ],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
