# Generated by Django 4.2.2 on 2024-10-08 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_alter_client_options_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="client",
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="client",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing.client",
                verbose_name="Клиенты рассылки",
            ),
            preserve_default=False,
        ),
    ]
