# Generated by Django 4.2.2 on 2024-09-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="date_publication",
            field=models.DateField(auto_now_add=True, verbose_name="Дата публикации"),
        ),
    ]
